version: "3.7"
services:
  bday_app:
    container_name: bday_app
    image: myapp
    ports:
      - "6000:6000" # listen
    environment:
      - "PGDB=test"
      - "PGUSER=test"
      - "PGPASS=test"
      - "PGHOST=192.168.11.171"
      - "PGPORT=5432"
    networks:
      - myapp
      
# External access to PG database      
networks:
  myapp:
    external: true
