version: "3.7"
services:
  helloapp:
    container_name: helloapp
    image: helloapp
    ports:
      - 6000:6000 # listen
    networks:
      - myapp
      
# External access to PG database      
networks:
  myapp:
    external: true
