version: "3.7"
services:
  bday_app:
    container_name: helloapp
    image: helloapp
    ports:
      - "6000:6000" # listen
    environment:
      - "POSTGRES_DB=test"
      - "POSTGRES_USER=test"
      - "POSTGRES_PASS=test"
      - "POSTGRES_HOST=192.168.11.171"
      - "POSTGRES_PORT=5432"
    networks:
      - myapp
      
# External access to PG database      
networks:
  myapp:
    external: true
