apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  selector:
    matchLabels:
      app: helloapp
  replicas: 2
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      containers:
      - name: helloapp
        image: "eu.gcr.io/encoded-mark-332220/helloapp"
        env:
          - name: POSTGRES_HOST
            value: 10.175.0.1
          - name: POSTGRES_USER
            value: test
          - name: POSTGRES_PASSWORD
            value: test
          - name: POSTGRES_DB
            value: tests
          - name: POSTGRES_PORT
            value: 5432
          - name: PORT
            value: 6000
