apiVersion: v1
kind: Service
metadata:
  name: hello-app
  labels:
    app: helloapp
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
    - port: 80
    - targetPort: 6000
  selector:
    app: helloapp