apiVersion: v1
kind: Service
metadata:
  name: postgres
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  labels:
    app: postgres
spec:
  type: LoadBalancer
  ports:
    - port: 5432
  selector:
    app: postgres