---
  
- name: Install essentials 
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - wget 
    - curl 
    - python3-dev
    - python3-pip
    - python3-docker
    - python3-setuptools
    - python3-wheel
    - python3-venv
    - virtualenv
    
- name: Add GPG keys
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
    state: present