---
- name: Fetch the repo from GitHub
  git:
    repo: 'https://github.com/RupGautam/py-flask-ansible-docker.git'
    clone: yes
    dest: ./flask-app
    force: yes

- name: Docker-compose up -d
  shell: docker-compose up -d --build --remove-orphans
  args:
    chdir: ./flask-app
