---
- name: Fetch the repo from GitHub
  git:
    repo: 'https://github.com/lesandie/flask-app.git'
    clone: yes
    dest: ./flask-app
    force: yes

- name: Docker build
  community.docker.docker_image:
    build:
      path: ./flask-app
    name: dnieto/helloapp
    tag: v1
    source: build

- name: docker-compose up
  community.docker.docker_compose:
    project_src: ./flask-app
    state: present
