---
- name: Create a directory if it does not exist
  file:
    path: "{{ path_repos }}/flask-app"
    state: directory
    mode: 0755


- name: Fetch the repo from GitHub
  git:
    repo: https://github.com/lesandie/flask-app.git
    clone: yes
    dest: "{{ path_repos }}/flask-app"
    force: yes

- name: Docker build and push to Registry
  community.docker.docker_image:
    build:
      path: "{{ path_repos }}/flask-app"
    name: "eu.gcr.io/{{ gcp_project }}/helloapp"
    tag: v1
    source: build
    push: yes

#Deploy locally for testing
- name: docker-compose up
  community.docker.docker_compose:
    project_src: "{{ path_repos }}/flask-app"
    state: present

