---
- name: Fetch the repo from GitHub
  git:
    repo: 'https://github.com/lesandie/flask-app.git'
    clone: yes
    dest: "{{ path_repos }}"
    force: yes

- name: Docker build
  community.docker.docker_image:
    build:
      path: "{{ path_repos }}/flask-app"
    name: dnieto/helloapp
    tag: v1
    source: build

- name: docker-compose up
  community.docker.docker_compose:
    project_src: "{{ path_repos }}/flask-app"
    state: present
