---
- name: Update cache and Install docker
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Enable docker services
  become: true
  systemd:
    name: docker
    enabled: yes
    masked: no

- name: Add non-root to docker group
  become: true
  user:
    name: "{{ raspi_user }}"
    groups: [docker]
    append: yes

- name: Install docker and docker-compose via pip
  pip:
    name:
      - docker
      - docker-compose
