---
- name: Install boostrap, docker and deploy
  hosts: all
  vars:
    raspi_user: dnieto
    path_repos: /home/dnieto/Repos
  #vars_files:
  #  - /vars/external_vars.yml
  become: yes
  become_method: sudo 

  roles:
    - boostrap
    - docker 
    - deploy 
